name: Sync Requirements to README

on:
  push:
    branches:
      - main # Or 'master' if that's your default branch
    paths:
      - 'requirements.md' # Trigger only when requirements.md changes
      - 'README.md'       # Also trigger if README.md is directly changed (e.g., to restore previous content)
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

permissions: # <--- ADD THIS BLOCK
      contents: write # <--- This grants write access to the repository content

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update README.md with requirements
        run: |
          python3 -c "
          import re
          
          # Read the requirements content
          with open('requirements.md', 'r', encoding='utf-8') as f:
              requirements_content = f.read()
          
          # Read the current README
          with open('README.md', 'r', encoding='utf-8') as f:
              readme_content = f.read()
          
          # Define the pattern to match content between markers
          pattern = r'(<!-- REQUIREMENTS_START -->).*?(<!-- REQUIREMENTS_END -->)'
          
          # Create the replacement content
          replacement = r'\1\n\n' + requirements_content + r'\n\n\2'
          
          # Replace the content
          new_readme_content = re.sub(pattern, replacement, readme_content, flags=re.DOTALL)
          
          # Write the updated README
          with open('README.md', 'w', encoding='utf-8') as f:
              f.write(new_readme_content)
          
          print('README.md updated successfully')
          "

      - name: Commit and Push if changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Docs: Auto-update README.md with requirements"
          branch: ${{ github.ref_name }} # Push to the same branch that triggered the action